export interface Project {
  id: string;
  title: string;
  subtitle?: string;
  description: string;
  liveUrl: string;
  playStoreUrl?: string;
  githubUrl?: string;
  technologies: string[];
  category: 'all' | 'fullstack' | 'animation-3d' | 'ecommerce' | 'fintech-ai' | 'realestate-health' | 'services';
  status: 'Live' | 'Production' | 'Featured' | 'In Progress';
  featured?: boolean;
  flagship?: boolean;
  metrics?: string;
  badge?: string;
  highlights?: string[];
}

export const projects: Project[] = [
  // 🌟 FLAGSHIP MASTERPIECES 🌟
  {
    id: 'urban-power',
    title: 'Urban Power: All Home Services (App & Web)',
    subtitle: 'Full-Stack Android App & Web Portal Ecosystem',
    description: 'Comprehensive multi-service on-demand ecosystem operating across Delhi NCR. Offers verified professional house help, appliance maintenance/repairs, doorstep beauty salon, domestic/bulk scrap buy & sell, and instant grocery delivery with 24/7 emergency dispatch.',
    liveUrl: 'https://rjurbanpower.in/',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=com.urbanpower.app&hl=en_IN',
    technologies: ['React Native', 'Android (Play Store)', 'Next.js', 'Node.js', 'PostgreSQL', 'Firebase OTP', 'Google Maps API', 'AWS S3'],
    category: 'fullstack',
    status: 'Production',
    featured: true,
    flagship: true,
    badge: '📱 Google Play Store v1.0.51',
    metrics: '90 MB • Android 7.0+ • 24/7 Live Support',
    highlights: [
      'House Help & Repairs: Plumbers, electricians, AC repair, carpenters, painters & pest control.',
      'Doorstep Salon: Certified beauticians for women & men, grooming packages, and academy courses.',
      'Scrap Buy & Sell: Digital weighing & instant payment for domestic, commercial & bulk scrap.',
      'Online Grocery: Fresh fruits, vegetables, kitchen staples with fast doorstep dispatch.',
      'Live Booking & OTP Auth: Real-time slot booking, live digital invoices, and AMC plans.',
    ],
  },
  {
    id: 'rankriseusa',
    title: 'RankRise USA - Digital Growth & Marketing Agency',
    subtitle: 'US-Based Corporate Marketing & SEO Platform',
    description: 'High-converting US digital marketing agency platform built from ground up. Features dynamic interactive lead-capture funnels, Core Web Vitals optimization, automated inquiry routing, and custom SEO structured schema.',
    liveUrl: 'https://rankriseusa.com/',
    technologies: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS', 'Framer Motion', 'Technical SEO', 'Lead Funnel'],
    category: 'services',
    status: 'Live',
    featured: true,
    flagship: true,
    badge: '🚀 US Agency Platform',
    metrics: '+35% Inbound Lead Conversion • 98 Core Web Vitals',
    highlights: [
      'High-converting interactive lead-generation funnel with smart form routing.',
      'Custom SEO architecture with rich JSON-LD schema for US search ranking.',
      'Silky smooth 60fps micro-animations and responsive mobile-first design.',
    ],
  },
  {
    id: 'digilik-agency',
    title: 'DigiQlik / Digilik - Digital Marketing & Branding',
    subtitle: 'Full-Service Digital Agency Web Platform',
    description: 'Modern digital agency website designed to drive brand acceleration, performance marketing, and creative campaigns. Built with responsive layouts, case-study sliders, and integrated conversion forms.',
    liveUrl: 'https://digilik.com/',
    technologies: ['React.js', 'Next.js', 'Tailwind CSS', 'Framer Motion', 'Node.js', 'REST API'],
    category: 'services',
    status: 'Live',
    featured: true,
    flagship: true,
    badge: '🌐 Digital Agency',
    metrics: '95+ Lighthouse Score • Multi-domain Deployment',
    highlights: [
      'Showcase of digital marketing, performance ads, and web development services.',
      'Interactive portfolio filtering and client testimonial carousel.',
      'Optimized for instant page transitions and high accessibility standards.',
    ],
  },
  {
    id: 'overseastars',
    title: 'Overseas Stars - Global Employee Outsourcing',
    subtitle: 'International Talent Recruitment & HR Platform',
    description: 'Enterprise employee outsourcing and global talent acquisition platform. Connects international businesses with vetted remote developers, customer support specialists, and back-office professionals.',
    liveUrl: 'https://overseastars.com/',
    technologies: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS', 'Lucide React', 'Vercel'],
    category: 'services',
    status: 'Live',
    featured: true,
    flagship: true,
    badge: '🌍 Global Outsourcing',
    metrics: 'Global Talent Pipeline • Enterprise Client Onboarding',
    highlights: [
      'International hiring workflows and candidate requirement matching engine.',
      'Comprehensive service tiers for tech, creative, and customer operations teams.',
      'Fast responsive interface with seamless international inquiry processing.',
    ],
  },
  {
    id: 'techforex',
    title: 'TechForex & Real-Time Trading Platform',
    subtitle: 'High-Frequency Forex & OHLCV Streams',
    description: 'Real-time financial trading platform aggregating live OHLCV price feeds via WebSocket streams. Features interactive candlestick charts, technical indicators (SMA, RSI, MACD), and TimescaleDB time-series storage.',
    liveUrl: 'https://techforex.in/',
    technologies: ['TypeScript', 'React', 'Node.js', 'TimescaleDB', 'PostgreSQL', 'WebSocket', 'Chart.js', 'Docker', 'AWS'],
    category: 'fintech-ai',
    status: 'Live',
    featured: true,
    flagship: true,
    badge: '⚡ Real-Time Trading',
    metrics: 'Sub-second WebSocket Tick Data • Dockerized on AWS',
    highlights: [
      'Sub-second real-time OHLCV market data aggregation via WebSockets.',
      'TimescaleDB time-series optimized backend on Docker & AWS.',
      'Interactive candlestick charting with live technical indicators.',
    ],
  },
  {
    id: 'lava-flow',
    title: 'Lava FlameFlow 3D Animation',
    subtitle: 'Procedural WebGL & Particle Simulation',
    description: 'Experimental fluid and lava dynamics animation utilizing WebGL, custom shader materials, GSAP timelines, and Three.js particle systems for immersive interactive rendering.',
    liveUrl: 'https://lava-flameflow-animation.netlify.app/',
    technologies: ['Three.js', 'WebGL', 'GSAP', 'GLSL Shaders', 'Canvas API'],
    category: 'animation-3d',
    status: 'Live',
    featured: true,
    flagship: true,
    badge: '🎨 WebGL 3D Simulation',
    metrics: '60 FPS Smooth Simulation • +18% CTR Lift',
    highlights: [
      'Custom GLSL fragment & vertex shaders for fluid lava temperature gradients.',
      'GPU-accelerated particle physics reacting to cursor inertia.',
    ],
  },

  // 3D / Animation & Creative Experience
  {
    id: 'digital-mark-3d',
    title: 'Digital Mark - 3D Fluid & Particles',
    subtitle: 'Creative Agency 3D Interactive Platform',
    description: 'High-end agency showcase featuring smooth fluid particle motion, scroll-driven WebGL scenes, interactive canvas shaders, and case-study sliders with zero frame drops.',
    liveUrl: 'https://digital-mark-seven.vercel.app/',
    technologies: ['Next.js', 'Three.js', 'Framer Motion', 'GSAP', 'Tailwind CSS'],
    category: 'animation-3d',
    status: 'Live',
    featured: true,
    metrics: 'Scroll Parallax • 95+ Performance Score',
  },
  {
    id: 'rangerover-3d',
    title: 'Range Rover 3D Configurator',
    subtitle: 'Real-Time WebGL Product Visualizer',
    description: 'Immersive interactive 3D car configurator featuring real-time colorway switching, alloy rim swaps, metallic shader materials, dynamic studio lighting, and smooth orbit camera controls.',
    liveUrl: 'https://rangerover3d.vercel.app/',
    technologies: ['React', 'Three.js', 'WebGL', 'GSAP', '3D Asset Optimization'],
    category: 'animation-3d',
    status: 'Live',
    featured: true,
    metrics: '2.4s Initial Load • 60 FPS WebGL',
  },
  {
    id: 'attention-seeker-3d',
    title: 'Attention Seeker 3D Portfolio',
    subtitle: 'Interactive 3D Spatial Developer Hub',
    description: 'Award-grade personal portfolio with floating distorted 3D meshes, starfields, dynamic mouse-parallax physics, and dark mode aesthetic designed for maximum developer impact.',
    liveUrl: 'https://attention-seeker-portfolio.vercel.app/',
    technologies: ['Next.js', 'Three.js', 'React Three Fiber', 'Drei', 'Framer Motion'],
    category: 'animation-3d',
    status: 'Live',
    featured: true,
  },
  {
    id: 'live-animation-login',
    title: 'Live Animation Login Experience',
    subtitle: 'Micro-interaction & Physics UI Showcase',
    description: 'Hyper-responsive login authentication interface with stateful input morphing, fluid button feedback, magnetic physics, and subtle particle backdrops.',
    liveUrl: 'https://live-animation-login-page.netlify.app/',
    technologies: ['React', 'Framer Motion', 'GSAP', 'CSS Modules'],
    category: 'animation-3d',
    status: 'Live',
  },
  {
    id: 'dj-intro',
    title: 'DJ Intro & Event Showcase',
    subtitle: 'Audio-Visual Sound Wave Experience',
    description: 'Dynamic event landing experience with high-energy typography animations, audio-reactive glow effects, and interactive event lineup schedule.',
    liveUrl: 'https://dj-intro.netlify.app/',
    technologies: ['React', 'CSS Keyframes', 'GSAP', 'HTML5 Audio'],
    category: 'animation-3d',
    status: 'Live',
  },
  {
    id: 'rubik-3d',
    title: 'Rubik\'s Cube 3D Simulator & Solver',
    subtitle: 'Mathematical 3D Puzzle with CFOP Hints',
    description: 'Full 3D Rubik\'s cube simulator with intuitive 3-axis drag-to-rotate controls, state scrambler, move history stack, and step-by-step CFOP algorithm solver hints.',
    liveUrl: 'https://rubik-game-sp.netlify.app/',
    technologies: ['React', 'Three.js', 'GSAP', 'CFOP Algorithm', 'TypeScript'],
    category: 'animation-3d',
    status: 'Live',
    metrics: '+3 min Avg Session • University Code Fair Feature',
  },

  // FinTech, AI & Real-Time Systems
  {
    id: 'my-first-crm',
    title: 'MyFirst CRM & Pipeline Visualizer',
    subtitle: 'Sales Forecasting & Funnel Analytics',
    description: 'Analytics-driven CRM platform featuring dynamic sales funnel tracking, conversion rate graphs, team task assignments, and automated PDF export reports.',
    liveUrl: 'https://my-first-crm.vercel.app/',
    technologies: ['React', 'Next.js', 'Node.js', 'MongoDB', 'Chart.js', 'Tailwind'],
    category: 'fullstack',
    status: 'Live',
    metrics: 'Active Sales Pipeline Dashboard',
  },
  {
    id: 'school-report-gen',
    title: 'Automated School Report Generator',
    subtitle: 'REST API Document Automation Engine',
    description: 'Automated batch report card generation engine converting student CSV datasets into pixel-perfect PDF report cards with grading analytics, saving teachers hours per exam cycle.',
    liveUrl: 'https://school-report-generator-eight.vercel.app/',
    technologies: ['React', 'Node.js', 'Express', 'Puppeteer', 'REST API', 'Bootstrap'],
    category: 'fullstack',
    status: 'Live',
    metrics: 'Used by 2 Schools • Eliminated 90% Data Errors',
  },

  // E-Commerce & Marketplaces
  {
    id: 'gharkamarket',
    title: 'GharKaMarket Local E-Commerce',
    subtitle: 'Hyperlocal Multi-Product Marketplace',
    description: 'Local retail e-commerce platform with merchant store onboarding, category search, real-time inventory management, checkout flow, and custom SEO structured schema.',
    liveUrl: 'https://gharkamarket.in/',
    technologies: ['React.js', 'Node.js', 'MongoDB', 'Payment Gateway', 'Structured SEO'],
    category: 'ecommerce',
    status: 'Live',
    featured: true,
    metrics: 'Top 15 Google Local Keywords • 90+ Mobile Usability',
  },
  {
    id: 'smartgadgetshop',
    title: 'Smart Gadget Shop',
    subtitle: 'High-Performance Electronics Store',
    description: 'Full-stack gadget e-commerce portal with instant live search, Redux cart state, JWT authentication, admin inventory portal, and Stripe checkout integration.',
    liveUrl: 'https://smartgadgetshop.netlify.app/',
    technologies: ['React.js', 'Node.js', 'Express', 'MongoDB', 'Redux Toolkit', 'Stripe'],
    category: 'ecommerce',
    status: 'Live',
    metrics: '95 Lighthouse Performance Score',
  },
  {
    id: 'headphonesonly',
    title: 'Headphones Only Audio Store',
    subtitle: 'Niche Acoustic Gear & Configurator',
    description: 'Specialized audio eCommerce platform with an interactive 3D sound profile configurator, coupon engine, dynamic urgency timers, and Core Web Vitals optimization.',
    liveUrl: 'https://headphonesonly.netlify.app/',
    technologies: ['React.js', 'Redux', 'Stripe', 'Tailwind CSS', 'CSS Keyframes'],
    category: 'ecommerce',
    status: 'Live',
    metrics: '+15% Conversion in A/B Tests • 92 SEO Score',
  },
  {
    id: 'shoppingappa',
    title: 'ShoppingApp Marketplace Simulator',
    subtitle: 'Multi-Vendor Commerce with CI/CD',
    description: 'Scalable multi-vendor store architecture with order tracking, automated GitHub Actions CI/CD deployment pipelines to Vercel, and zero-downtime releases.',
    liveUrl: 'https://shoppingappa.netlify.app/',
    technologies: ['React.js', 'Redux', 'Stripe', 'GitHub Actions', 'Node.js'],
    category: 'ecommerce',
    status: 'Live',
  },

  // Healthcare & Hospitality
  {
    id: 'dna-repcom',
    title: 'DNA Repcom Lab Cancer Specialist Institute',
    subtitle: 'Clinical Research & Healthcare Portal',
    description: 'Comprehensive medical institute portal with specialist doctor directories, patient appointment booking flow, clinical lab services overview, and accessible UX.',
    liveUrl: 'https://dna-repcom-lab.vercel.app/',
    technologies: ['Next.js', 'React', 'Tailwind CSS', 'Lucide Icons', 'Vercel'],
    category: 'realestate-health',
    status: 'Live',
    featured: true,
  },
  {
    id: 'royal-rajasthan-rasoi',
    title: 'Royal Rajasthan Rasoi Luxury Dining',
    subtitle: 'Heritage Restaurant & Table Booking Suite',
    description: 'Immersive royal themed restaurant portal with interactive culinary menus, Google Calendar API table reservation engine, and mobile-first responsive layout.',
    liveUrl: 'https://royalrajasthanrasoi.com/',
    technologies: ['React.js', 'Tailwind CSS', 'Google Calendar API', 'Vercel Deployment'],
    category: 'services',
    status: 'Live',
    metrics: '90+ Lighthouse Performance • +25% Mobile Engagement',
  },
  {
    id: 'shivraj-hotel',
    title: 'Shivraj Hotel & Hospitality Suite',
    subtitle: 'Hotel Room Booking & Amenities Hub',
    description: 'Full-featured hospitality portal showcasing luxury suites, banquet halls, local tour guides, and contactless booking inquiry engine.',
    liveUrl: 'https://shivrajhotel.vercel.app/',
    technologies: ['React', 'Bootstrap 5', 'EmailJS', 'Responsive UX'],
    category: 'services',
    status: 'Live',
    metrics: '+30% Inquiry Conversion Increase',
  },

  // Real Estate & Infrastructure
  {
    id: 'villaoptions',
    title: 'Villa Options Luxury Real Estate',
    subtitle: 'Mobile-First Property Listing & Map Index',
    description: 'High-end villa catalog with structured schema markup, search filters by location and amenities, Google Analytics heatmap tracking, and fast page loads.',
    liveUrl: 'https://villaoptions.netlify.app/',
    technologies: ['HTML5/CSS3', 'JavaScript', 'Structured Data Schema', 'Core Web Vitals'],
    category: 'realestate-health',
    status: 'Live',
    metrics: '+40% Organic Search Traffic • -22% Bounce Rate',
  },
  {
    id: 'mero-vrindavan',
    title: 'Mero Vrindavan Dham Township',
    subtitle: 'Spiritual Real Estate & Plot Showcase',
    description: 'Modern real estate landing platform highlighting gated township master plans, interactive layout plot selectors, and direct WhatsApp / call inquiry bridges.',
    liveUrl: 'https://merovrindavandham.vercel.app/',
    technologies: ['React', 'Tailwind CSS', 'Framer Motion', 'Vercel'],
    category: 'realestate-health',
    status: 'Live',
  },
  {
    id: 'bella-decor',
    title: 'Bella Decor Art Gallery & Interiors',
    subtitle: 'Curated Architectural Decor Gallery',
    description: 'Aesthetic art gallery and interior architecture website featuring high-resolution image galleries, product lookbooks, and luxury aesthetic styling.',
    liveUrl: 'https://bella-decor-bella-decor.vercel.app/',
    technologies: ['Next.js', 'React', 'Tailwind CSS', 'Framer Motion'],
    category: 'realestate-health',
    status: 'Live',
  },
  {
    id: 'mohan-residency',
    title: 'Mohan Residency Premium Homes',
    subtitle: 'Residential Housing & Floorplans',
    description: 'Property showcase portal with architectural 2D/3D floorplans, neighborhood amenity guides, mortgage inquiry calculator, and fast mobile UX.',
    liveUrl: 'https://real-estate-mohan-residency.vercel.app/',
    technologies: ['React', 'Tailwind CSS', 'Lucide React', 'Vercel'],
    category: 'realestate-health',
    status: 'Live',
  },

  // Utility, Services & Education
  {
    id: 'yoga-convent-school',
    title: 'Yoga Convent School Portal',
    subtitle: 'Institutional Website & Admissions Hub',
    description: 'Educational portal for school admissions, academic calendars, faculty directories, annual photo galleries, and WCAG 2.1 AA accessible interface.',
    liveUrl: 'https://yogaconventschool.in/',
    technologies: ['React', 'Tailwind CSS', 'JavaScript', 'Accessible UI (WCAG AA)'],
    category: 'services',
    status: 'Live',
    metrics: 'WCAG 2.1 AA Accessible • -20% Bounce Rate',
  },
  {
    id: 'gasxpert',
    title: 'GasXpert Utility & Technical Services',
    subtitle: 'Commercial Gas Pipeline & Appliance Service',
    description: 'Service dispatch portal for residential and industrial gas pipeline installation, safety inspection bookings, and 24/7 emergency technician dispatch.',
    liveUrl: 'https://gasxpert.in/',
    technologies: ['React', 'Tailwind CSS', 'SEO Optimization', 'Lead Capture Form'],
    category: 'services',
    status: 'Live',
  },
  {
    id: 'yes-gas-service',
    title: 'Yes Gas Service Maintenance Hub',
    subtitle: 'Instant Gas Appliance Technician Booking',
    description: 'High-speed local service booking application for gas stove, hob, and pipeline repairs with instant WhatsApp booking integration.',
    liveUrl: 'https://yesgasservice.in/',
    technologies: ['HTML5/CSS3', 'JavaScript', 'Responsive UI', 'WhatsApp API'],
    category: 'services',
    status: 'Live',
  },
  {
    id: 'gaschimneycare',
    title: 'Gas & Chimney Care Support',
    subtitle: 'Kitchen Appliance Care & Dispatch',
    description: 'Home appliance repair and scheduled maintenance booking web application with multi-city technician dispatch routing.',
    liveUrl: 'https://gaschimneycare-testing.netlify.app/',
    technologies: ['React', 'Tailwind CSS', 'Netlify CD', 'Dynamic Form'],
    category: 'services',
    status: 'Live',
  },
];

export const categories = [
  { id: 'all', label: 'All Projects (25+)' },
  { id: 'fullstack', label: 'Full Stack & Mobile Apps' },
  { id: 'services', label: 'Agencies & Corporate Platforms' },
  { id: 'fintech-ai', label: 'FinTech, Real-Time & AI' },
  { id: 'animation-3d', label: '3D, WebGL & Animations' },
  { id: 'ecommerce', label: 'E-Commerce & Marketplaces' },
  { id: 'realestate-health', label: 'Real Estate & Healthcare' },
];
